QuizGame/Models/Answer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace QuizGame.Models
{
    public class Answer
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public int QuestionId { get; set; }

        public virtual Question Question { get; set; }

        [Required]
        public string Text { get; set; }

        [Required]
        [DefaultValue(false)]
        public bool Correct { get; set; }
    }
}

QuizGame/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace QuizGame.Models
{
    public class Question
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [Column(TypeName = "ntext")]
        public string Text { get; set; }

        public virtual ICollection<Answer> Answers { get; set; }
    }
}

QuizGame/Models/QuizGameContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace QuizGame.Models
{
    public class QuizGameContext : DbContext
    {
        public DbSet<Question> Questions { get; set; }
        public DbSet<Answer> Answers { get; set; }

        public QuizGameContext() : base("DefaultConnection") 
        {
        }
    }
}

QuizGame/Models/QuizMode.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuizGame.Models
{
    public enum QuizMode
    {
        Binary = 1,
        MultipleChoice = 2
    }
}

QuizGame/Models/QuizSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuizGame.Models
{
    static class QuizSettings
    {
        public static QuizMode DefaultQuizMode()
        {
            return QuizMode.Binary;
        }
    }
}

QuizGame/ViewModels/QuestionViewModel.cs
using QuizGame.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuizGame.ViewModels
{
    public class QuestionViewModel
    {
        public QuestionViewModel()
        {
            QuizMode = QuizSettings.DefaultQuizMode().ToString();
        }

        public Question NextQuestion { get; set; }

        public string Text { get; set; }

        public string QuizMode { get; set; }

        List<Answer> _answers;

        public List<Answer> Answers
        {
            get { return _answers; }
            set
            {
                _answers = value;
                SetRandomAnswer();
            }
        }

        public string Question
        {
            get
            {
                return "Who said it?";
            }
        }

        public Answer RandomAnswer { get; set; }

        public bool IsLast
        {
            get
           {
                return NextQuestion == null;
            }
        }

        private void SetRandomAnswer()
        {
            var random = new Random();
            int i = random.Next(Answers.Count);
            RandomAnswer = Answers[i];
        }
    }
}

QuizGame/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuizGame.Models;

namespace QuizGame.Controllers
{
    public class AnswersController : Controller
    {
        private QuizGameContext db = new QuizGameContext();
        
        public ActionResult Validate(int id, bool consideredTrue = true)
        {
            var answer = db.Answers.Find(id);
            if(answer == null)
            {
                return new HttpNotFoundResult();
            }

            var correctAnswer = answer.Text;
            if (!answer.Correct)
            {
                correctAnswer = answer.Question.Answers.Where(a => a.Correct).FirstOrDefault()?.Text;
            }

            var guessedCorrectly = answer.Correct == consideredTrue;

            var result = new {
                correct = answer.Correct,
                guessedCorrectly = guessedCorrectly,
                message = guessedCorrectly ? "Correct! The right answer is: …" : "Sorry, you are wrong! The right answer is: …",
                correctAnswer = correctAnswer
            };

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuizGame/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuizGame.Models;
using QuizGame.ViewModels;

namespace QuizGame.Controllers
{
    public class QuestionsController : Controller
    {
        private QuizGameContext db = new QuizGameContext();

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            Question question = null;
            if (id == null)
            {
                question = db.Questions.First();
            }
            else
            {
                question = db.Questions.Find(id);
            }

            if (question == null)
            {
                return HttpNotFound();
            }

            var quizMode = Session["QuizMode"];

            var nextQuestion =  db.Questions.Where(q => q.Id > question.Id).FirstOrDefault();

            var vm = new QuestionViewModel() { NextQuestion = nextQuestion, Text = question.Text, Answers = question.Answers.ToList() };

            if (quizMode != null)
            {
                vm.QuizMode = quizMode.ToString();
            }

            return View(vm);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuizGame/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuizGame.Models;

namespace QuizGame.Controllers
{
    public class QuizController : Controller
    {
        public ActionResult Settings()
        {
            if(Session["QuizMode"] == null)
            {
                Session["QuizMode"] = QuizSettings.DefaultQuizMode().ToString();
            }

            ViewBag.QuizMode = Session["QuizMode"];

            return View();
        }

        [HttpPost]
        public ActionResult Settings(string Mode)
        {
            if(Enum.IsDefined(typeof(QuizMode), Mode))
            {
                Session["QuizMode"] = Mode;
            }
            
            return RedirectToAction("Details", "Questions");
        }
    }
}

QuizGame/Views/Questions/Details.cshtml
@model QuizGame.ViewModels.QuestionViewModel

@{
    ViewBag.Title = "Famous Quote Quiz";
}

<h1 class="heading">Famous Quote Quiz</h1>

<div class="quiz__container">
    <div class="question__container">
        <div class="question__intro">
            @Html.DisplayFor(model => model.Question)
        </div>

        <div class="question__text">
            @Html.DisplayFor(model => model.Text)
        </div>
    </div>

    <div class="answers__container--binary js-binary-mode">
        <div class="quiz__suggested-answer js-suggested-answer" data-answer-id="@Model.RandomAnswer.Id">@Html.DisplayFor(model => model.RandomAnswer.Text)?</div>

        <div class="answer__options">
    <div class="answer--yes js-answer-yes">Yes</div>
    <div class="answer--no js-answer-no">No</div>
</div>
    </div>

    <div class="answers__container--multiple-choice js-multiple-choice-mode">
        @foreach (var answer in Model.Answers)
        {
            <div class="question__answer js-answer-mutiple-choice" data-answer-id="@answer.Id">@answer.Text</div>
        }
    </div>

    <div class="quiz__result js-quiz-result">
    </div>
    <div class="quiz__correct-answer js-quiz-correct-answer">
    </div>

    <div class="quiz__next-question js-next-question">
        @if (Model.IsLast)
        {
            <a href="/" class="quiz__next-question--link">Start again the quiz</a>
        }
        else
        {
            @Html.ActionLink("Next", "Details", "Questions", new { id = Model.NextQuestion.Id }, new { @class = "quiz__next-question--link" })
        }
    </div>
</div>

<div data-quiz-mode="@Model.QuizMode" class="mode__info js-quiz-mode">
    Mode: @Model.QuizMode - @Html.ActionLink("Change", "Settings", "Quiz")
</div>

QuizGame/Views/Quiz/Settings.cshtml
@model Enum

@{
    ViewBag.Title = "Quiz mode";
}
<h1 class="heading">Quiz mode</h1>

@using (Html.BeginForm("Settings", "Quiz", FormMethod.Post, new { @class = "quiz__settings-form" }))
{

    foreach (var value in Enum.GetValues(typeof(QuizGame.Models.QuizMode)))
    {
        <div class="quiz_settings--option">
            @Html.RadioButton("Mode", value, (string)ViewBag.QuizMode == value.ToString())
            @Html.Label(value.ToString())
        </div>
    }

    <input type="submit" value="Save" class="btn btn-default quiz__settings-form--submit" />

    @Html.ActionLink("Back to the quiz", "Details", "Questions")
}

QuizGame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/quiz")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>